// Generated by CoffeeScript 1.12.7
(function() {
  var BannedEffect, DefaultEffect,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DefaultEffect = require('./defaultEffect');

  BannedEffect = (function(superClass) {
    extend(BannedEffect, superClass);

    function BannedEffect() {
      return BannedEffect.__super__.constructor.apply(this, arguments);
    }

    BannedEffect.prototype.banned = function() {
      return true;
    };

    return BannedEffect;

  })(DefaultEffect);

  module.exports = BannedEffect;

}).call(this);
