// Generated by CoffeeScript 1.12.7
(function() {
  var CritRateEffect, DefaultEffect,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DefaultEffect = require('./defaultEffect');

  CritRateEffect = (function(superClass) {
    extend(CritRateEffect, superClass);

    function CritRateEffect() {
      return CritRateEffect.__super__.constructor.apply(this, arguments);
    }

    CritRateEffect.prototype.criticalRateStage = function() {
      switch (this.id) {
        case 44:
        case 201:
        case 210:
          return 1;
        case 289:
          return 50;
      }
    };

    CritRateEffect.prototype.buildMultiplier = function(attacker) {
      switch (this.id) {
        case 44:
        case 201:
        case 210:
          return 1.03;
        case 289:
          return 1.5;
      }
    };

    CritRateEffect.prototype.battleMultiplier = function(attacker, defender, damage, lethal) {
      switch (this.id) {
        case 44:
        case 201:
        case 210:
          return 1.03;
        case 289:
          return 1.5;
      }
    };

    return CritRateEffect;

  })(DefaultEffect);

  module.exports = CritRateEffect;

}).call(this);
