// Generated by CoffeeScript 1.12.7
(function() {
  var DefaultEffect;

  DefaultEffect = (function() {
    function DefaultEffect(id, chance) {
      this.id = id;
      this.chance = chance;
    }

    DefaultEffect.prototype.power = function(base) {
      return base;
    };

    DefaultEffect.prototype.effectiveness = function(effectiveness, attacker, defender) {
      return effectiveness;
    };

    DefaultEffect.prototype.hits = function() {
      return 1;
    };

    DefaultEffect.prototype.criticalRateStage = function() {
      return 0;
    };

    DefaultEffect.prototype.buildMultiplier = function(attacker) {
      return 1;
    };

    DefaultEffect.prototype.battleMultiplier = function(attacker, defender, damage, lethal) {
      return 1;
    };

    DefaultEffect.prototype.afterDamage = function(attacker, defender, damage, log) {};

    DefaultEffect.prototype.afterMiss = function(attacker, defender, log) {};

    DefaultEffect.prototype.banned = function() {
      return false;
    };

    DefaultEffect.prototype.fullSupport = function() {
      return this.constructor.name !== 'DefaultEffect';
    };

    return DefaultEffect;

  })();

  module.exports = DefaultEffect;

}).call(this);
