// Generated by CoffeeScript 1.12.7
(function() {
  var DefaultEffect, DoublePowerEffect,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DefaultEffect = require('./defaultEffect');

  DoublePowerEffect = (function(superClass) {
    extend(DoublePowerEffect, superClass);

    function DoublePowerEffect() {
      return DoublePowerEffect.__super__.constructor.apply(this, arguments);
    }

    DoublePowerEffect.prototype.power = function(base, attacker, defender) {
      return base * 2;
    };

    return DoublePowerEffect;

  })(DefaultEffect);

  module.exports = DoublePowerEffect;

}).call(this);
