// Generated by CoffeeScript 1.12.7
(function() {
  var DefaultEffect, MultiHitEffect,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DefaultEffect = require('./defaultEffect');

  MultiHitEffect = (function(superClass) {
    extend(MultiHitEffect, superClass);

    function MultiHitEffect() {
      return MultiHitEffect.__super__.constructor.apply(this, arguments);
    }

    MultiHitEffect.prototype.hits = function() {
      switch (this.id) {
        case 30:
          return [2, 2, 3, 3, 4, 5][Math.floor(Math.random() * 6)];
        case 45:
        case 78:
          return 2;
      }
    };

    MultiHitEffect.prototype.buildMultiplier = function(attacker) {
      switch (this.id) {
        case 30:
          return 3.166;
        case 45:
        case 78:
          return 2;
      }
    };

    MultiHitEffect.prototype.battleMultiplier = function(attacker, defender, damage, lethal) {
      if (!lethal) {
        switch (this.id) {
          case 30:
            return 3.166;
          case 45:
          case 78:
            return 2;
        }
      } else {
        return 1;
      }
    };

    return MultiHitEffect;

  })(DefaultEffect);

  module.exports = MultiHitEffect;

}).call(this);
