// Generated by CoffeeScript 1.12.7
(function() {
  var DefaultEffect, RecoilOnMissEffect,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DefaultEffect = require('./defaultEffect');

  RecoilOnMissEffect = (function(superClass) {
    extend(RecoilOnMissEffect, superClass);

    function RecoilOnMissEffect() {
      return RecoilOnMissEffect.__super__.constructor.apply(this, arguments);
    }

    RecoilOnMissEffect.prototype.buildMultiplier = function(attacker) {
      return 0.9;
    };

    RecoilOnMissEffect.prototype.battleMultiplier = function(attacker, defender, damage, lethal) {
      return 0.9;
    };

    RecoilOnMissEffect.prototype.afterMiss = function(attacker, defender, log) {
      var recoil;
      recoil = Math.min(Math.floor(attacker.maxHp / 2), attacker.hp);
      attacker.hp -= recoil;
      return log.message(attacker.trainerAndName() + " kept going and crashed for " + recoil + " HP!");
    };

    return RecoilOnMissEffect;

  })(DefaultEffect);

  module.exports = RecoilOnMissEffect;

}).call(this);

//# sourceMappingURL=recoilOnMissEffect.js.map
