// Generated by CoffeeScript 1.12.7
(function() {
  var StatusAilment;

  StatusAilment = (function() {
    function StatusAilment() {}

    StatusAilment.prototype.inflict = function(pokemon, log) {
      var key;
      key = this.constructor.name;
      pokemon.conditions[key] = this;
      return this.whenInflicted(pokemon, log);
    };

    StatusAilment.prototype.isInflicted = function(pokemon) {
      var key;
      key = this.constructor.name;
      return pokemon.conditions[key] != null;
    };

    StatusAilment.prototype.heal = function(pokemon) {
      var key;
      key = this.constructor.name;
      return delete pokemon.conditions[key];
    };

    StatusAilment.prototype.whenInflicted = function(pokemon, log) {};

    StatusAilment.prototype.canAttack = function(pokemon, log) {
      return true;
    };

    StatusAilment.prototype.endTurn = function(pokemon, log) {};

    StatusAilment.prototype.buildMultiplier = function(attacker, chance) {
      return 1;
    };

    StatusAilment.prototype.battleMultiplier = function(attacker, defender, chance) {
      return 1;
    };

    return StatusAilment;

  })();

  module.exports = StatusAilment;

}).call(this);
