// Generated by CoffeeScript 1.12.7
(function() {
  var Log;

  Log = (function() {
    function Log() {
      this.log = [];
      this.turn = 0;
      this.attack = 0;
    }

    Log.prototype.message = function(str) {
      if (this.log[this.turn] == null) {
        this.log[this.turn] = [];
      }
      if (this.log[this.turn][this.attack] == null) {
        this.log[this.turn][this.attack] = [];
      }
      return this.log[this.turn][this.attack].push(this.upperFirst(str));
    };

    Log.prototype.endAttack = function() {
      return this.attack++;
    };

    Log.prototype.endTurn = function() {
      this.turn++;
      return this.attack = 0;
    };

    Log.prototype.toString = function() {
      var attack, i, j, k, len, len1, len2, message, ref, str, turn;
      str = '';
      ref = this.log;
      for (i = 0, len = ref.length; i < len; i++) {
        turn = ref[i];
        for (j = 0, len1 = turn.length; j < len1; j++) {
          attack = turn[j];
          for (k = 0, len2 = attack.length; k < len2; k++) {
            message = attack[k];
            str += message + "\n";
          }
          str += "\n";
        }
        str += "\n";
      }
      return str.trim();
    };

    Log.prototype.upperFirst = function(str) {
      return str.charAt(0).toUpperCase() + str.slice(1);
    };

    return Log;

  })();

  module.exports = Log;

}).call(this);
