// Generated by CoffeeScript 1.12.7
(function() {
  var BurnStatusAilment, StatusAilment,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  StatusAilment = require('./statusAilment');

  BurnStatusAilment = (function(superClass) {
    extend(BurnStatusAilment, superClass);

    function BurnStatusAilment() {
      return BurnStatusAilment.__super__.constructor.apply(this, arguments);
    }

    BurnStatusAilment.prototype.affects = function(pokemon) {
      var type;
      return indexOf.call((function() {
        var i, len, ref, results;
        ref = pokemon.types;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          type = ref[i];
          results.push(type.name);
        }
        return results;
      })(), 'Fire') < 0;
    };

    BurnStatusAilment.prototype.whenInflicted = function(pokemon, log) {
      return log.message(pokemon.trainerAndName() + " was burned!");
    };

    BurnStatusAilment.prototype.endTurn = function(pokemon, log) {
      return pokemon.takeDamage(Math.round(pokemon.maxHp / 8), "%(pokemon) was hurt %(damage) by its burn!", log);
    };

    BurnStatusAilment.prototype.statMultiplier = function(stat) {
      switch (stat) {
        case 'attack':
          return 0.5;
        default:
          return 1;
      }
    };

    BurnStatusAilment.prototype.battleMultiplier = function(chance) {
      return 1 + 0.5 * chance / 100;
    };

    return BurnStatusAilment;

  })(StatusAilment);

  module.exports = BurnStatusAilment;

}).call(this);
