// Generated by CoffeeScript 1.12.7
(function() {
  var StatusAilment;

  StatusAilment = (function() {
    function StatusAilment() {}

    StatusAilment.prototype.affects = function(pokemon) {
      return true;
    };

    StatusAilment.prototype.whenInflicted = function(pokemon, log) {};

    StatusAilment.prototype.whenSwitchedOut = function(pokemon) {};

    StatusAilment.prototype.canAttack = function(pokemon, log) {
      return true;
    };

    StatusAilment.prototype.endTurn = function(pokemon, log) {};

    StatusAilment.prototype.statMultiplier = function(stat) {
      return 1;
    };

    StatusAilment.prototype.battleMultiplier = function(chance) {
      return 1;
    };

    return StatusAilment;

  })();

  module.exports = StatusAilment;

}).call(this);
